name: Build Branch

on: workflow_dispatch

env:
  # CMake build type to upload (Release, Debug, RelWithDebInfo, etc.)
  upload-build-type: Release

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
        build-type: [ Debug, Release ]

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -A Win32 -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DSHA=${{github.sha}} -DENABLE_BH_TESTS=ON

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build-type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{matrix.build-type}}

    - uses: actions/upload-artifact@v2
      if: ${{matrix.build-type ==  env.upload-build-type}}
      with:
        name: BH.dll
        path: build/Release/BH.dll
